version: "3"

services:
  php:
    image: php:${PHP_VERSION}
    volumes:
      - ~/.composer-docker/cache:/var/www/.composer/cache
      - ./:/app
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
      - ./docker/php/.bashrc:/var/www/.bashrc
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
      COMPOSER_MEMORY_LIMIT: -1
    restart: ${RESTART}
    depends_on:
      - db

  nginx:
    image: nginx:1.19.8-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated
    restart: ${RESTART}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${DOCKER_DOMAIN},${ADMIN_DOMAIN}"
    networks:
      - default
      - web
    depends_on:
      - php

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DOCKER_DB_PORT}:5432
    restart: ${RESTART}

  redis:
    image: redis:6.2.1-alpine
    ports:
      - 127.0.0.1:${DOCKER_REDIS_PORT}:${REDIS_PORT}
    restart: ${RESTART}

  node:
    image: node:14.16.0-alpine
    user: "node"
    working_dir: /app
    volumes:
      - ./:/app:delegated
    command: /bin/true

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  db_data:

networks:
  web:
    external: true
